M48
; DRILL file {KiCad 7.0.5} date Fri Jun 16 17:13:36 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-06-16T17:13:36-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.500
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.000
%
G90
G05
T2
X9.056Y-44.488
X9.056Y-51.688
T3
X15.738Y-27.278
T1
G00X10.006Y-43.958
M15
G01X10.606Y-43.958
M16
G05
T0
M30
